[package]
name = "builtonbits"
version = "1.0.0"
authors = ["Douglas Adams <douglasryanadams@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
